In [1]:
import numpy as np

In [2]:
vec = np.array([1,2,3])
vec.ndim

1

In [4]:
mat = np.array ([[1,2,3], [4,5,6]])
mat.ndim

2

In [5]:
vec.shape

(3,)

In [6]:
mat.shape

(2, 3)

In [7]:
mat.dtype.name

'int32'

In [8]:
vec.dtype.name

'int32'

In [9]:
mat.itemsize

4

In [10]:
vec.itemsize

4

In [11]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [12]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [13]:
B = np.array ([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
A.dtype.name
B.dtype.name

'int32'

In [15]:
print(A.dtype.name)

float64


In [16]:
A.itemsize

8

In [17]:
A.shape

(3,)

In [18]:
np.zeros((3,))

array([0., 0., 0.])

In [19]:
np.ones ((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty((2,5))

array([[8.91342776e-312, 2.32210854e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 6.18618429e+223, 3.18650123e-110,
        2.91237123e+257, 4.71294503e+257]])

In [23]:
np.empty((5,5))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.11261434e-306, 2.22522868e-306],
       [1.78022342e-306, 6.23058028e-307, 1.22389333e-307,
        1.33508760e-307, 1.42417221e-306],
       [1.37961641e-306, 8.34424342e-308, 8.34426039e-308,
        1.22387550e-307, 1.11261027e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306],
       [6.89805151e-307, 1.78020169e-306, 1.42410974e-306,
        9.34604357e-307, 2.56765117e-312]])

In [24]:
np.empty((1,))

array([2.56765117e-312])

In [25]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [26]:
np.arange(2.5, 8.0, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [27]:
np.linspace(2,18,14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [29]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.arange(8).reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
C = np.arange(6).reshape(2,-1)

NameError: name 'np' is not defined

In [4]:
np.arange(6).reshape(2,-1)

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
C = np.arange(6).reshape(2,-1)

In [7]:
C


array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
C.T
C

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [10]:
A = np.arange(6).reshape(2,-1)
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [11]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [12]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [13]:
a = np.arange(3)

In [14]:
a


array([0, 1, 2])

In [17]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [18]:
np.tile(a, (0,0))

array([], shape=(0, 0), dtype=int32)

In [19]:
np.tile(a, (1,1))

array([[0, 1, 2]])

In [20]:
np.tile(a, (3,5))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [21]:
np.tile(a, (4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [22]:
A = np.arange(9).reshape(3,3)
B = np.arange(1,10).reshape(3,3)

In [24]:
print (A)
print (B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [26]:
A * 1.0

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [27]:
A / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [28]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [30]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [31]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [32]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [33]:
np.tile(np.arange(0,40,10),(3,1)).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [40]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [42]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
A.min()

0

In [53]:
A.max(axis = 0)

array([6, 7, 8])

In [54]:
A.sum(axis = 1)

array([ 3, 12, 21])

In [55]:
a = np.arange(10)
a
a[2:5]

array([2, 3, 4])

In [56]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a[1:2:3]

array([1])

In [60]:
a[0:0:0]

ValueError: slice step cannot be zero

In [61]:
a[2:6:8]

array([2])

In [62]:
a[3:8:2]

array([3, 5, 7])

In [63]:
A = np.arange(81).reshape(9,-1)

In [64]:
A


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [65]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [66]:
A[3:6]

array([[27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53]])

In [67]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [68]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [69]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [70]:
A = np.arange(81).reshape(9,-1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [71]:
A[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [72]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
A[A%5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [74]:
A[np.logical_and(A != 7, A%5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [79]:
import time
A_quick_arr = np.random.normal(size = (100000,))
B_quick_arr = np.random.normal(size = (100000,))
A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [103]:
start = time.time()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.time() - start)

0.037897348403930664


In [107]:
a = time.time()
b = time.time()
print(b - a)

0.0


In [109]:
c = time.perf_counter()
d = time.perf_counter()
print (d - c)

2.6200000320386607e-05


In [110]:
start = time.time()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.time() - start)

0.006971836090087891


In [111]:
start = time.time()
ans = A_quick_arr.dot(B_quick_arr)
print(time.time() - start)

0.007952690124511719
